parser: babel-eslint
env:
  browser: true
  commonjs: true
  es6: true
  node: true
parserOptions:
  sourceType: module
  ecmaVersion: 8
extends: [
  'plugin:flowtype/recommended',
  'eslint:recommended'
]
plugins: ['flowtype']
