cache:
  directories:
    - node_modules
language: node_js
node_js:
  - "8"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run build
  - npm run cov
  - npm run report-coverage
  - npm run lint
